CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

CREATE TABLE customers_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    full_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),
    city VARCHAR(255),
    state VARCHAR(100),
    preferred_dealership_id BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_customers_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE TABLE leads_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    customer_id BIGINT,
    vehicle_id BIGINT,
    dealership_id BIGINT,
    title VARCHAR(255),
    description VARCHAR(1000),
    urgency VARCHAR(50),
    status VARCHAR(50),
    source VARCHAR(100),
    created_at TIMESTAMP,
    converted_at TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_leads_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE TABLE user_type_aud (
    id VARCHAR(255) NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    type VARCHAR(255),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_user_type_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE TABLE users_aud (
    id VARCHAR(255) NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    username VARCHAR(255),
    email VARCHAR(255),
    hashed_password VARCHAR(255),
    cpf VARCHAR(255),
    last_login TIMESTAMP,
    user_type VARCHAR(255),
    mfa_secret VARCHAR(255),
    mfa_enabled BOOLEAN,
    refresh_token VARCHAR(255),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_users_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);
