CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;
ALTER TABLE revinfo ALTER COLUMN rev DROP IDENTITY IF EXISTS;
ALTER TABLE revinfo ALTER COLUMN rev SET DEFAULT nextval('revinfo_seq');
